global:
  log_level: "INFO"
  warcraft_vods:
    directory: "D:\\Videos\\WoW"
    file_types: 
      - ".mp4"
    search_keywords: 
      - "Kill"
    difficulties:
      # - "Heroic"
      - "Mythic"
  youtube_video:
    description: "Killed at {killed_at} on {difficulty}"
    tags:
      - "Warcraft"
      - "Kill"
      - "{difficulty}"
    visibility: "unlisted"
  authentication:
    directory: "./auth"
    client_secrets_file: "client_secret.json"
    token_file: "token.json"
  database:
    directory: "."
    name: "wow_vods.db"
    